- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:

  - name: Update All Packages
    yum:
      name: '*'
      state: latest

  - name: Install Apache
    yum: 
      name: httpd
      state: installed

  - name: Start Apache
    service:
      name: httpd
      state: started
    
  - name: Create The HTML File
    shell: echo "Hello Frank Nwanze, THANK YOU." > /var/www/html/index.html
    args:
      executable: /bin/bash
    notify:
      - Reload Apache
 
  handlers:
    - name: Reload Apache
      service:
        name: httpd
        state: reloaded