---
# tasks file for update
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: yes

- name: Update all apps
  ansible.builtin.apt:
    name: '*'
    state: latest