---
# tasks file for nodejs-latest

- name: Add NodeSource repository
  apt:
    deb: "https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main"   #VAR
    state: present
  register: add_repo
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Add NodeSource GPG key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Install Node.js
  apt:
    name: nodejs
    state: present
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Update cache and install Node.js on CentOS
  yum:
    name: nodejs
    state: present
    enablerepo: epel
  when: ansible_distribution == "CentOS"
