- name: Ping and update
  hosts: all
  remote_user: ubuntu # ec2-user
  become: true
  gather_facts: false

  tasks:
    - name: Ping hosts
      ansible.builtin.ping:
  roles:
    - update

- name: Upload files to backend
  hosts: backend
  remote_user: ubuntu # ec2-user
  become: true
  become_user: root

  roles:
    - nginx
    - nodejs
    - copy-folder
  vars:
    folder_dest: "/home/ubuntu/Library-app/"
    folder_src: "backend/"
    node_version: 22
    ansible_distribution: "Ubuntu"

- name: Upload files to frontend
  hosts: frontend
  remote_user: ubuntu # ec2-user
  become: true
  become_user: root

  roles:
    - nginx
    - nodejs
    - copy-folder
  vars:
    folder_dest: "/home/ubuntu/Library-app/"
    folder_src: "frontend/"
    node_version: 22
    ansible_distribution: "Ubuntu"

- name: Set up monitor servers
  hosts: monitors
  become: true
  remote_user: ubuntu # ec2-user

  roles:
    - prometheus
    - grafana

- name: Install node-exporter
  hosts: nodeservers
  become: true
  roles:
    - node-exporter
