#!/usr/local/bin/ansible-playbook
- name: Testiing connection
  hosts: engineering
  remote_user: ec2-user
  become: true
  become_user: root

  roles:
    - update
    - nginx
    - shell

  tasks:
    - name: Ping hosts
      ansible.builtin.ping:
