- name: Testiing connection
  hosts: web-apps
  remote_user: ubuntu # ec2-user
  become: true
  become_user: root

  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

  roles:
    - update
    - nginx
    - nodejs
    - copy-folder
  vars:
    node_version: 16
