#!/usr/local/bin/ansible-playbook
- name: Testiing connection
  hosts: engineering
  remote_user: ubuntu # ec2-user
  become: true
  become_user: root

  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

  roles:
    - nginx
    - update
    - shell
